dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848


spring:
  application:
    name: dubbo-web


server:
  port: 8084


api:
  registerAddress: 127.0.0.1:8848
  env: dev
  gray: false